version: '3'
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "80:3001"
    command: "npm run start:fast"
    networks:
      - "cheety_back_net"
  nosql:
    image: mongo
    ports:
      - 3021:27017
    networks:
      - "cheety_back_net"
    volumes:
      - "./volumes/nosql:/data/db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=D8A7pxav"
networks:
  cheety_back_net:
    driver: bridge
volumes:
  cheety-nodemodules: