version: "3.9"

services:

  node:
    image: cheety-back
    depends_on:
      - nosql
    networks:
      - kn-net
    expose:
      - 3009:3009

  nosql:
    image: mongo
    networks:
      - kn-net
    expose:
      - 3010:27017
    volumes:
      - kn-cheety-db:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=D8A7pxav
      - MONGO_INITDB_DATABASE=cheety

networks:
  kn-net:
    driver: bridge

volumes:
  kn-cheety-db: